
#+OPTIONS: num:nil
#+OPTIONS: toc:nil

* Some thoughts on gender and division of labor (draft)

If you notice carefully the gender questions (such as equality vs equity / fair competition vs efficiency etc) almost exclusively arise in the context of modern workplace environments (eg: Management / IT / Academia etc) where the means and modes of production are sophisticated. In contrast, in relative under-developed settings (eg: agriculture, construction works, handicrafts  etc) where the entire family (the man, the woman and the children) 'have to' go to work together in order to survive, these questions are seldom asked.

** What can we understand from this difference?
   - Gender bias is counter productive to capitalism - that's the reason gender conflicts continue to emerge with advancement in the means of production (the more developed a country is the more these issues are discussed). On the other hand, it is not so much of an issue for a slower (and more localized and less organized) feudal mode of production we see in rural India. As a matter of fact the family structures and gender relations are in sync (historically adjusted) with the pace at which feudal mode production operates. This is the reason why gender questions seldom surface in a rural contexts. Or, the gender questions are settled within the system of prevailing culture/logic without calling for any revolutionary movement per se.

** Capitalism is progressive so far as the gender question is concerned.
   - I claim that in modern work environments (undertaken in capitalist mode of production) gender imbalance actually hinders growth. If a 'human-resource' is efficient and can evidently add value to an organization, a modern company doesn't have to give one shit if it's a woman, a  man, or what part of gender spectrum they belong. Decisions made with gender bias in mind (instead of optimizing profits) will prove detrimental for an organization. Why? Simply because there is no evidence that men can fair better than women in any of the modern sectors - so no effort to undermine a resource based on their gender will prove to be profitable. Therefore, like everything else that capitalism crushes for coming in its way, gender imbalance is going to be one. For its own good, capitalism is walking the 'progressive' path in this context. Remember it doesn't care about absolute 'emancipation' of women directly -- it just does what is good for its productivity. This 'emancipation' of a woman from financial dependency would liberate her spiritually but only partially. Since she is still a captive of capitalism, her 'ideals and dreams' are still very much going to be within the confines of market economy. She's an independent consumer of the market now! While we may not call this the ultimate liberation it definitely a push towards progress.

** How can we call it progress?
   - Now the conflict is between capitalism and patriarchy. Capitalism operates with fast paced, sophisticated skills, (controlled yet) rational outlook for things, and exposes women to global cultures and progressive tendencies. This spiritual emancipation of a women (although only partial), particularly the sexual freedom  she may secure as a result is a threat to patriarchy. What the heck patriarchy anyway? Patriarchy is basically the remnant from the past -- gender relations that got solidified under the past mode of productions - simple as that. Basically patriarchy is a habit, rather a practice, a mode of division of labor that gave the beastly humans an edge in the forest. The gender roles and labor distribution kept changing as the mode of production evolved. Also, at any given snapshot of history, the gender roles also depend on the 'class' of concern. I'm sure agree with this. Melinda Gates's problems are so different from problems of a housewife in Pakistan and wife of a fisherman on the shore of Vizag! Their 'fates' are essentially intertwined with the economical system around them. Each of these are progressing at their own pace.

** Feminism?
  - From what I understand the conventional feminism is capitalist expression (of disapproval) of prevailing gender relations. This is not bad. It is definitely progress. May not be the kind of progress that a socialist would aspire to see, but this will eventually contribute to that (this is my personal belief). Women are joining the work force these days not necessarily because they found their ultimate purpose of life but because they get to afford a 3 bedroom flat! You see? That's the kind of equality that this is all leading to. Women are going to as clueless as men under capitalism :) They are going to be trapped in market web aspiring to buy stuff at their own 'free will'. Dudes like bikes, chicks will fashion - both liberated! Free to buy anything they want (from the menu) by selling their labor. So capitalism will anyway take care of all this even if we don't do anything. There's a good reason why feminism is actually so mainstream! You saw how Microsoft is shitting pants to guard the image of Bill Gates? because it knows that this perception is going effect their business! Corporations have already surrendered to the scientific fact that women can be as efficient as men - there's nothing further to prove there. The direction has already been set. Work place equality, equity and whatever it is - all that will be done. Not because Jesus will punish but because that's what is fiscally optimal! The current feminist movements thrive to accelerate this development. Which is fine actually. Smashing of patriarchy will happen - there's not stopping.

** What can be done?
  - Theoretically there's nothing sacred about anything that is in existence. 'Existing' economy, 'existing' idea of family, 'existing' myth of culture, 'exiting' markets  etc. True revolutionaries think beyond there conceptual constraints. We can take a brave and critical take on all these things. Conventional feminists seek 'emancipation' of women within a capitalist mode of production, by demanding for maternity leaves, increasing no. of women CEOs etc. This according to me is a very weak stand and reflects on the lack of critical analysis of economy which is the root of all inequalities. Also, why should women be worried about 'ladies only' issues? Why can't their thinkers like Galileo, Newton, Darwin and Marx who spoke for the entire humanity? I personally think this 'ladies only issues' are 
